language: java
install:
- mvn install
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: BNDx48jMuan3ofqzewIly815D6pvnV8rVun87wrAMUAqVrh+kd2ysS1q0MvDBEM7kk7Wwz4d0IZb/V4tx94cXuSnjRKYm3lS8l+3ycNFBf+q+CGxcTsufmroZUBZv3UXJ0N7oRWGvzI8KLC9yTwsCZNPHjNuXxCdvn1ZWLO3eGbtt+Y0jXLaD2IS6//O8LwUqrdcdfLZ7AoX9PrM55ixRG5D2zBYQGsaQsxz9yTKHBZvEVUdKE2RTzsBEzKJBYia+FPBhIzU1SeaKtbY2BRJuVLB9oVztYCaQKv1yQSCiJ0VAHkXKf5n3ZL/MjodVZf3OpSSCZa7M4jyUSugS4ZcxiswhifYy3fChuEeR4+qYS7EJHjducJa1NkrvVjYYce7SsYZPdh0PCODttjI2b4QjqsY2EEkpmMF7vgjETH/JOjNfpaewvCmWdYX52GjGsdEv6K0zVtwoIhn/jVZJWykXi9I5/3If35PhHzsm5mwcBN/rWNV+dTg57K9Yc8igeTikP0wLtnFMFlPJuoYevrKsIZ0LuipBN/3sLhPZkHbXem8gTjWZwvhAlLev09WE7Yni1OtfSkgl5kV5ppiqkNLc4y0hwVvfxhCa7PJ7kzAxaDlV/zkdZ4BruEvq//09yz7PKB4E909f1E/r4sgV8SbSy083k9oY0aTXkx/xRZ73e4=
  app: undinediteration2
  on:
    repo: JonathanPrall/Undefined
    branch: Iteration2-master
